# Generated by Django 5.1.2 on 2024-11-13 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_pet_description_pet_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='bread',
            new_name='breed',
        ),
    ]
