# Generated by Django 5.1.2 on 2024-11-14 17:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_rename_bread_pet_breed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_pets', to=settings.AUTH_USER_MODEL),
        ),
    ]
