# Generated by Django 5.1.3 on 2024-12-11 08:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0007_alter_pet_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.PositiveSmallIntegerField(default=1, help_text='Age is represented in months.', validators=[django.core.validators.MinValueValidator(1, 'Age must be greater than 0'), django.core.validators.MaxValueValidator(240, 'Age must be less than 240')]),
        ),
    ]
