# Generated by Django 5.1.2 on 2024-11-22 19:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionFeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('for_pet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='for_pet', to='pets.pet')),
                ('from_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='accounts.userprofile')),
                ('to_shelter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_shelter', to='accounts.shelterprofile')),
            ],
        ),
    ]
