# Generated by Django 5.1.2 on 2024-11-24 13:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_shelterprofile_website'),
        ('core', '0001_initial'),
        ('pets', '0005_pet_gender_pet_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShelterRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adopter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adopter', to='accounts.userprofile')),
                ('adoption_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pets.adoptionrequest')),
                ('shelter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shelter', to='accounts.shelterprofile')),
            ],
            options={
                'unique_together': {('shelter', 'adopter')},
            },
        ),
        migrations.DeleteModel(
            name='AdoptionFeedBack',
        ),
    ]
