# Generated by Django 5.1.2 on 2024-11-25 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_shelterprofile_website'),
        ('core', '0003_contactform'),
        ('pets', '0005_pet_gender_pet_size'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shelterrating',
            unique_together={('shelter', 'adopter', 'adoption_request')},
        ),
    ]
