# Generated by Django 5.1.2 on 2024-11-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_shelterrating_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelterrating',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3, null=True),
        ),
    ]
