# Generated by Django 5.1.3 on 2024-11-28 17:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_shelterrating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelterrating',
            name='feedback',
            field=models.TextField(max_length=500, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(500, message='Feedback must be between 10 and 500 characters')]),
        ),
    ]
