# Generated by Django 5.1.2 on 2024-11-09 14:56

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 50 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=50, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='province',
            field=models.CharField(choices=[('Blagoevgrad', 'Blagoevgrad'), ('Burgas', 'Burgas'), ('Dobrich', 'Dobrich'), ('Gabrovo', 'Gabrovo'), ('Haskovo', 'Haskovo'), ('Kardzhali', 'Kardzhali'), ('Kyustendil', 'Kyustendil'), ('Lovech', 'Lovech'), ('Montana', 'Montana'), ('Pazardzhik', 'Pazardzhik'), ('Pernik', 'Pernik'), ('Pleven', 'Pleven'), ('Plovdiv', 'Plovdiv'), ('Razgrad', 'Razgrad'), ('Ruse', 'Ruse'), ('Shumen', 'Shumen'), ('Silistra', 'Silistra'), ('Sliven', 'Sliven'), ('Smolyan', 'Smolyan'), ('Sofia City', 'Sofia City'), ('Sofia Province', 'Sofia Province'), ('Stara Zagora', 'Stara Zagora'), ('Targovishte', 'Targovishte'), ('Varna', 'Varna'), ('Veliko Tarnovo', 'Veliko Tarnovo'), ('Vidin', 'Vidin'), ('Vratsa', 'Vratsa'), ('Yambol', 'Yambol')], max_length=60),
        ),
    ]
