# Generated by Django 5.1.2 on 2024-11-15 20:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelterprofile',
            name='organization',
        ),
        migrations.AddField(
            model_name='shelterprofile',
            name='organization_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
