# Generated by Django 5.1.2 on 2024-11-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_shelterprofile_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelterprofile',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
