# Generated by Django 5.1.2 on 2024-11-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_shelterprofile_user_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelterprofile',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
