# Generated by Django 5.1.2 on 2024-11-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_shelterprofile_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelterprofile',
            name='rating',
        ),
        migrations.AlterField(
            model_name='shelterprofile',
            name='website',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
