# Generated by Django 5.1.3 on 2024-11-30 09:41

import PetAdoption.accounts.validators
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_shelterprofile_organization_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with that email already exists.'}, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='type_user',
            field=models.CharField(choices=[('Adopter', 'Adopter'), ('Shelter', 'Shelter')], default='Adopter', error_messages={'invalid': "Invalid user type. Please select 'Adopter' or 'Shelter'."}, max_length=7, validators=[PetAdoption.accounts.validators.validate_type_user]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.', 'username': ['This field may contain only letters, digits and @/./+/-/_ characters.']}, max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(3), django.contrib.auth.validators.UnicodeUsernameValidator()]),
        ),
        migrations.AlterField(
            model_name='shelterprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number must contain only digits, spaces, parentheses, and dashes.', max_length=13, null=True, validators=[PetAdoption.accounts.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(error_messages={'invalid': 'The first name can only contain letters.', 'max_length': 'The first name must not exceed 30 characters.', 'min_length': 'The first name must be at least 2 characters long.'}, help_text='Must contain only letters and be between 2 and 30 characters long.', max_length=30, validators=[django.core.validators.MinLengthValidator(2, message='The first name must be at least 2 characters long.'), PetAdoption.accounts.validators.validate_letters_only]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(error_messages={'invalid': 'The last name can only contain letters.', 'max_length': 'The last name must not exceed 30 characters.', 'min_length': 'The last name must be at least 2 characters long.'}, help_text='Must contain only letters and be between 2 and 30 characters long.', max_length=30, validators=[django.core.validators.MinLengthValidator(2, message='The last name must be at least 2 characters long.'), PetAdoption.accounts.validators.validate_letters_only]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number must contain only digits, spaces, parentheses, and dashes.', max_length=13, null=True, validators=[PetAdoption.accounts.validators.validate_phone_number]),
        ),
    ]
